---
- name: Getting you ready for lab3
  hosts: host:leaf
  gather_facts: no
  become: yes
  tasks:
    - name: Dropping in config
      copy:
        src: lab3-configurations/{{inventory_hostname}}/config.yaml
        dest: /etc/netplan/config.yaml
      notify: apply interface config
   
  handlers:
    - name: apply interface config
      become: yes
      command: netplan apply 

